name: CI
on:
  push:
    branches:
      - "*"

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]
        pnpm-version: ["8.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Cache pnpm dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Build applications
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm type-check
