name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  CI:
    name: Checking code quality
    runs-on: ubuntu-latest
    environment: Production

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
      
    - name: Restore cached npm dependencies
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
        key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts
      
    - name: Cache pnpm dependencies
      uses: actions/cache/save@v4
      with:
        path: |
          node_modules
        key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Lint
      run: pnpm lint
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

    - name: Type check
      run: pnpm type-check

    - name: Build
      run: npx nx run-many --all --target=build
